spring.application.name=freelanceos
spring.datasource.url=jdbc:postgresql://ep-nameless-base-aihhkdix.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1GxvYMWfqu9N

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
